
import pygame

# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Pygame Maze"

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
GOLD = (255, 215, 0)


# Maze settings
CELL_SIZE = 20
MAZE_WIDTH = SCREEN_WIDTH // CELL_SIZE
MAZE_HEIGHT = SCREEN_HEIGHT // CELL_SIZE
WALL_COLOR = BLUE
PATH_COLOR = BLACK

# Character settings
CHARACTER_SIZE = CELL_SIZE // 2
CHARACTER_COLOR = GREEN
START_COLOR = GREEN
END_COLOR = GOLD


# Game settings
FPS = 60
